version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - haskell-code-explorer-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack setup
      - run:
          name: Build
          command: stack -j 2 build --test --no-run-tests
      - run:
          name: Run tests
          command: stack test || stack exec --no-ghc-package-path $(stack path --dist-dir)/build/test/test
      - save_cache:
          name: Cache Dependencies
          key: haskell-code-explorer-{{ checksum "stack.yaml" }}
          paths:
            - "/root/.stack"
            - "/root/.cache"
            - ".stack-work"
